### ISSUE TITLE
install guide

### ISSUE THREAD

**Issue by chrisduk112** [badguy99/octoblock#12]
HI

I have built a new Home Assistant on RaspberryPi and installed Hecs.

I need more information on how you install your addon?  Where do I go to on HECS on the left to find/install this addon?

**Comment by badguy99** [comment]
Click on the HACS "C" icon on the left menu, then "Automation" followed by the Yellow + in the bottom right corner. Then search for "octoblock" the Search for Repository window that comes up.

I'm not really a fan of the new HACS look, it is harder to browse for things now. Hope this helps though.

**Comment by chrisduk112** [comment]
when I click HACS on the left i have:

Integrations
Frontend
About

I dont see automation?

**Comment by chrisduk112** [comment]
I also tried adding the folder octobock to 

\\homeassistant.local\config\appdaemon\apps

and edited apps.yaml to

```
octoblock:
  module: octoblock
  class: OctoBlock
  region: H
  use_timezone: False
  blocks:
    - hour: 1
      import: True
      start_period: now
      name: octopus_1hour
    - hour: 1.5
      start_period: today
      name: octopus_vacuum
      limits:
        start_time: '07:00'
        end_time: '16:00'
    - hour: 2
      import: True
      start_period: now
    - hour: 0
      start_period: now
      name: octopus_current_import
    - hour: 0
      export: True
      import: False
      start_period: now
      name: octopus_current_export
  lookaheads:
    - price: 3.0
      operation: below
      and_equal: True
      duration_ahead: 12
      name: hw_via_electric_not_gas

```


I then rebooted it 
i still cant find a way to see an app for octoblock
