### ISSUE TITLE
Help with trigger time block please

### ISSUE THREAD

**Issue by ryanteck** [badguy99/octoblock#17]
Hi,

I'm trying to get the time period blocks working again, however still can't seem to get it to work.

I've attached my config which is as per the updated documentation.
```

- id: '1600873207709'
  alias: EV Charger On
  description: ''
  trigger:
  - platform: template
    value_template: '{% if (states("sensor.date_time_iso") + (" BST"))  == (states("sensor.octopus_1hour_time"))
      or (states("sensor.date_time_iso") + (" GMT"))  == (states("sensor.octopus_1hour_time"))
      -%} True {%- endif %}'
  condition:
  - below: '8.45'
    condition: numeric_state
    entity_id: sensor.octopus_current_price
  - condition: state
    entity_id: switch.tasmota
    state: 'off'
  action:
  - device_id: d55cf96b74f94890b17b54175159bd79
    domain: switch
    entity_id: switch.tasmota
    type: turn_on

```

![Screenshot from 2020-10-28 10-04-30](https://user-images.githubusercontent.com/1104745/97422026-2454cc00-1905-11eb-9b86-75f20594ce16.png)
